In [15]:
#1

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(a)  



[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
#2

m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [36]:
#3

m_5x5 = np.random.randint(1, 11, size=(5, 5))

print(m_5x5)


[[ 2  9  6  7  8]
 [10 10  2  5  8]
 [ 7  9  6  3  1]
 [ 9  5  3  6  6]
 [10  4  3  8  3]]


In [45]:
#4

m_4x4 = np.random.rand(4, 4)

print(m_4x4)

[[0.28629541 0.55125674 0.06750252 0.36603366]
 [0.69505438 0.06734196 0.21498403 0.94794292]
 [0.40918075 0.35423688 0.82947493 0.30655049]
 [0.81487356 0.94665758 0.20998251 0.27431611]]
