In [56]:
#1

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=int)
print(a)  



[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
#2

m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
#3

m = np.random.randint(1, 11, size=(5, 5))
print(m)


[[ 2  9  9  6  2]
 [ 6  6  5  9  9]
 [ 6 10  6  8  8]
 [ 7 10  2  8  7]
 [10  9  8  9  4]]


In [35]:
#4

m = np.random.rand(4, 4)
print(m)

[[0.87752024 0.46394846 0.87884569 0.72105548]
 [0.60633904 0.96493837 0.54480969 0.46321349]
 [0.78796692 0.9918662  0.24852464 0.97173049]
 [0.90302306 0.74444478 0.57377177 0.64682428]]


In [36]:
#5

a = np.random.randint(1, 11, size=5)
print("Масив 1:", a)

b = np.random.randint(1, 11, size=5)
print("Масив 2:", b)

add_result = np.add(a, b)
print("Додавання:", add_result)

subtract_result = np.subtract(a, b)
print("Віднімання:", subtract_result)

multiply_result = np.multiply(a, b)
print("Множення:", multiply_result)

Масив 1: [1 1 1 6 4]
Масив 2: [2 6 3 2 1]
Додавання: [3 7 4 8 5]
Віднімання: [-1 -5 -2  4  3]
Множення: [ 2  6  3 12  4]


In [67]:
#6

a = np.random.randint(1, 11, size=7)
print(a)

b = np.random.randint(1, 11, size=7)
print(b)

scalar_mul = np.dot(a, b)
print(scalar_mul)


[3 9 4 5 9 1 1]
[ 2  3  2  3  5 10  4]
115


In [38]:
#7

m1 = np.random.randint(1, 11, size=(2, 2))
print(m1)

m2 = np.random.randint(1, 11, size=(2, 3))
print(m2)

matrix_multiply = np.dot(m1, m2)
print(matrix_multiply)

[[ 2  1]
 [ 2 10]]
[[ 9 10  4]
 [ 3  1  7]]
[[21 21 15]
 [48 30 78]]


In [39]:
#8

m = np.random.randint(1, 11, size=(3, 3))
print(m)

m_inv = np.linalg.inv(m)
print(m_inv)

[[ 8  5  4]
 [ 5  8  5]
 [ 1 10  8]]
[[ 0.13333333  0.         -0.06666667]
 [-0.33333333  0.57142857 -0.19047619]
 [ 0.4        -0.71428571  0.37142857]]


In [60]:
#9

m = np.random.rand(4, 4)
print(m)

m_T = np.transpose(m)
print(m_T)

[[0.22075427 0.14888046 0.05012348 0.74233643]
 [0.94674301 0.69471663 0.55814719 0.46291316]
 [0.47363197 0.0436076  0.92420062 0.72288506]
 [0.59584435 0.81467731 0.38648052 0.58658446]]
[[0.22075427 0.94674301 0.47363197 0.59584435]
 [0.14888046 0.69471663 0.0436076  0.81467731]
 [0.05012348 0.55814719 0.92420062 0.38648052]
 [0.74233643 0.46291316 0.72288506 0.58658446]]


In [72]:
#10

m = np.random.randint(1, 11, size=(3, 4))
print(m)

a = np.random.randint(1, 11, size=4)
print(a)

multiply_m_a= np.dot(m, a)
print(multiply_m_a)

[[ 9  3  9  3]
 [ 3  2 10  9]
 [ 3  6  1  8]]
[8 6 1 4]
[111  82  93]


In [76]:
#11

m = np.random.rand(2, 3)
print(m)

a = np.random.rand(3)
print(a)

multiply_m_a= np.dot(m, a)
print(multiply_m_a)

[[0.08130823 0.15011819 0.85861555]
 [0.74319597 0.06811173 0.87580051]]
[0.10899037 0.03646906 0.4924313 ]
[0.43714565 0.51475676]


In [85]:
#12

m1 = np.random.rand(2, 2)
print(m1)

m2 = np.random.rand(2, 2)
print(m2)

# m3 = np.multiply(m1, m2)
# print(m3)
print(m1*m2)

[[0.67838293 0.62817791]
 [0.37267862 0.05336141]]
[[0.73428634 0.42129557]
 [0.33987871 0.91309018]]
[[0.49812732 0.26464857]
 [0.12666553 0.04872378]]


In [88]:
#13

m1 = np.random.rand(2, 2)
print(m1)

m2 = np.random.rand(2, 2)
print(m2)

m3 = np.dot(m1, m2)
print(m3)

[[0.62231179 0.53947675]
 [0.42534944 0.92688648]]
[[0.94289484 0.02003427]
 [0.12275308 0.04671865]]
[[0.65299701 0.03767119]
 [0.51483797 0.05182445]]


In [89]:
#14

m = np.random.randint(1, 101, size=(5, 5))
print(m)

m_sum = np.sum(m)
print(m_sum)

[[92 47 34 66 54]
 [60 37 57 78 73]
 [86 71 55  7 95]
 [58 60 16 31 19]
 [18 93 80 17 67]]
1371


In [90]:
#15

m1 = np.random.randint(1, 11, size=(4, 4))
print(m1)

m2 = np.random.randint(1, 11, size=(4, 4))
print(m2)

m_difference = np.subtract(m1, m2)
print(m_difference)

[[9 8 4 9]
 [2 3 9 8]
 [7 1 4 6]
 [8 2 2 6]]
[[ 1 10 10 10]
 [ 8  3  9  2]
 [ 5  5  5  4]
 [ 8 10  7  5]]
[[ 8 -2 -6 -1]
 [-6  0  0  6]
 [ 2 -4 -1  2]
 [ 0 -8 -5  1]]


In [92]:
#16

m = np.random.rand(3, 3)
print(m)

a_sums = np.sum(m, axis=1, keepdims=True)
print(a_sums)

[[0.29386428 0.15620738 0.52202536]
 [0.62825436 0.65387121 0.18160934]
 [0.71493423 0.73559379 0.71605283]]
[[0.97209702]
 [1.46373491]
 [2.16658084]]


In [93]:
#17

m = np.random.randint(1, 11, size=(3, 4))
print(m)

m_square = np.square(m)
print(m_square)

[[6 9 7 9]
 [5 7 1 3]
 [5 2 2 6]]
[[36 81 49 81]
 [25 49  1  9]
 [25  4  4 36]]


In [95]:
#18

a = np.random.randint(1, 51, size=4)
print(a)

a_sqrt = np.sqrt(a)
print(a_sqrt)

[23 38 47 15]
[4.79583152 6.164414   6.8556546  3.87298335]
